# Generated by Django 5.1.7 on 2025-03-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmain',
            old_name='name',
            new_name='roll_no',
        ),
    ]
