# Generated by Django 5.1.7 on 2025-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_name_studentmain_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmain',
            name='email',
        ),
        migrations.AddField(
            model_name='studentmain',
            name='college_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='personal_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
