# Generated by Django 5.1.7 on 2025-04-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCategory',
            fields=[
                ('admission_category', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('blood_group', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('caste', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('seat_matrix_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentmain',
            name='year',
        ),
        migrations.AddField(
            model_name='studentmain',
            name='caste_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='creamy_layer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='ews_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='local_guardian_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='local_guardian_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='local_guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='mobile_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='non_creamy_layer_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='parent_contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='parent_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='permanent_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='pwd_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='college_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='roll_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='studentmain',
            name='admission_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.admissioncategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='blood_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.bloodgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='caste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.caste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmain',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.gender'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentDataEntry',
            fields=[
                ('personal_mail', models.EmailField(max_length=254, unique=True)),
                ('college_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('creamy_layer', models.BooleanField(default=False)),
                ('orphan', models.BooleanField(default=False)),
                ('pwd', models.BooleanField(default=False)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=15)),
                ('parent_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.TextField()),
                ('annual_income', models.CharField(blank=True, max_length=20, null=True)),
                ('local_guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('local_guardian_address', models.TextField(blank=True, null=True)),
                ('local_guardian_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('hostel_no_dues', models.CharField(blank=True, max_length=50, null=True)),
                ('mess_no_dues', models.CharField(blank=True, max_length=50, null=True)),
                ('address_proof', models.CharField(blank=True, max_length=255, null=True)),
                ('caste_validity_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('income_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('caste_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('ews_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('pwd_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_confirmation_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('college_fee_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('non_creamy_layer_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=None, null=True)),
                ('admission_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.admissioncategory')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.bloodgroup')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.branch')),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.caste')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.class')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.gender')),
            ],
        ),
    ]
