# Generated by Django 5.1.7 on 2025-04-10 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_admissioncategory_bloodgroup_branch_caste_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmain',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
