# Generated by Django 5.1.7 on 2025-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_studentmain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmain',
            name='parent_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='parent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
    ]
