# Generated by Django 5.1.7 on 2025-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_studentmain_parent_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmain',
            name='creamy_layer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='pwd',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
