# Generated by Django 5.2 on 2025-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_studentmain_creamy_layer_alter_studentmain_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdataentry',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='class_name',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='class_name',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmain',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='studentdataentry',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='students_documents/forms/'),
        ),
        migrations.AddField(
            model_name='studentdataentry',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/address_proofs/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='admission_confirmation_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/admission_confirmation/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='caste_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/caste_cert/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='caste_validity_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/caste_validity/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='college_fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/fee_receipt/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='ews_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/ews/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='hostel_no_dues',
            field=models.FileField(blank=True, null=True, upload_to='students_documents/hostel_no_dues/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/income/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='mess_no_dues',
            field=models.FileField(blank=True, null=True, upload_to='students_documents/mess_no_dues/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='non_creamy_layer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/ncl_certificate/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='pwd_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/pwd/'),
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
