# Generated by Django 5.1.7 on 2025-04-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_studentdataentry_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdataentry',
            name='entrance_exam',
            field=models.CharField(blank=True, choices=[('jee_mains', 'JEE Mains'), ('mht_cet', 'MHT-CET')], help_text='Required for First Year students (JEE Mains or MHT-CET).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdataentry',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='roll_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='StudentMain',
        ),
    ]
