# Generated by Django 5.1.7 on 2025-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_studentdataentry_entrance_exam_studentdataentry_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdataentry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
