# Generated by Django 5.1.7 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_studentdataentry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('warden', 'Warden'), ('rector', 'Rector'), ('manager', 'Manager')], default='student', max_length=10),
        ),
    ]
