# Generated by Django 5.1.7 on 2025-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_studentdataentry_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_name',
            field=models.CharField(blank=True, choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], default='ty', help_text='Only applicable for students', max_length=10, null=True),
        ),
    ]
