# Generated by Django 5.1.7 on 2025-04-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_customuser_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdataentry',
            name='branch_rank',
            field=models.IntegerField(blank=True, help_text='Rank within branch and gender', null=True),
        ),
    ]
