# Generated by Django 5.1.7 on 2025-05-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_customuser_user_type'),
        ('authentication', '0014_studentdataentry_branch_rank'),
    ]

    operations = [
    ]
