# Generated by Django 5.1.7 on 2025-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20250512_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDataVerification',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('class_name', models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], help_text='Year of the student', max_length=10)),
            ],
        ),
    ]
