# Generated by Django 5.1.7 on 2025-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_studentdataverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='seat_allocation_weight',
            field=models.IntegerField(default=1),
        ),
    ]
