# Generated by Django 5.1.7 on 2025-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20250529_0500'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='authenticat_year_8383f2_idx',
            old_name='authentication_branch_year_idx',
        ),
        migrations.RenameIndex(
            model_name='caste',
            new_name='authenticat_year_8a1521_idx',
            old_name='authentication_caste_year_idx',
        ),
        migrations.AlterField(
            model_name='branch',
            name='seat_allocation_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
