# Generated by Django 5.1.7 on 2025-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_rename_authentication_branch_year_idx_authenticat_year_8383f2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdataentry',
            name='last_selection_year',
            field=models.CharField(blank=True, choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdataentry',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
