# Generated by Django 5.1.7 on 2025-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_studentdataentry_last_selection_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdataentry',
            name='is_manually_modified',
            field=models.BooleanField(default=False),
        ),
    ]
