# Generated by Django 5.1.7 on 2025-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_studentdataentry_is_manually_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdataentry',
            name='is_manually_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
