# Generated by Django 5.1.7 on 2025-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_studentdataentry_is_manually_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdataentry',
            name='is_manually_modified',
        ),
        migrations.RemoveField(
            model_name='studentdataentry',
            name='last_selection_year',
        ),
        migrations.AddField(
            model_name='studentdataentry',
            name='seat_alloted',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
