# Generated by Django 5.1.7 on 2025-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_studentdataentry_is_manually_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdataentry',
            name='backlogs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
