# Generated by Django 5.1.7 on 2025-06-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_studentdataentry_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdataverification',
            name='backlogs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdataverification',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.caste'),
        ),
        migrations.AddField(
            model_name='studentdataverification',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdataverification',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdataverification',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdataverification',
            name='class_name',
            field=models.CharField(blank=True, choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], help_text='Year of the student', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdataverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
