# Generated by Django 5.2 on 2025-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_studentdataverification_backlogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdataentry',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='admission_confirmation_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='students_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='caste_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='caste_validity_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='college_fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='ews_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='hostel_no_dues',
            field=models.FileField(blank=True, null=True, upload_to='students_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='mess_no_dues',
            field=models.FileField(blank=True, null=True, upload_to='students_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='non_creamy_layer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='pwd_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
    ]
