# Generated by Django 5.1.7 on 2025-04-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_block_floor_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='hostel_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_maps/'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.room')),
                ('room_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='allotment.roomgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['room_group', 'rank'], name='allotment_p_room_gr_6ba595_idx')],
                'unique_together': {('room_group', 'room')},
            },
        ),
    ]
