# Generated by Django 5.1.7 on 2025-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_floor_hostel_map_image_preference'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='block',
            name='allotment_b_gender_69870c_idx',
        ),
        migrations.RemoveField(
            model_name='block',
            name='year',
        ),
        migrations.AddField(
            model_name='block',
            name='class_name',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], default='fy', max_length=10),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='class_name',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], default='fy', max_length=10),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['gender', 'class_name'], name='allotment_b_gender_836496_idx'),
        ),
    ]
