# Generated by Django 5.1.7 on 2025-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0004_remove_block_allotment_b_gender_69870c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='block',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
