# Generated by Django 5.1.7 on 2025-05-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0005_remove_room_capacity_block_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='capacity',
            new_name='per_room_capacity',
        ),
    ]
