# Generated by Django 5.1.7 on 2025-05-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0006_rename_capacity_block_per_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominvite',
            name='status',
        ),
    ]
