# Generated by Django 5.1.7 on 2025-05-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0007_remove_roominvite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominvite',
            name='timestamp',
        ),
    ]
