# Generated by Django 5.1.7 on 2025-05-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0008_remove_roominvite_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='block',
            name='allotment_b_gender_836496_idx',
        ),
        migrations.RemoveField(
            model_name='block',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='block',
            name='gender',
        ),
        migrations.AddField(
            model_name='floor',
            name='class_name',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Final Year')], default='fy', max_length=10),
        ),
        migrations.AddField(
            model_name='floor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['name'], name='allotment_b_name_ea824f_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['gender', 'class_name'], name='allotment_f_gender_163482_idx'),
        ),
    ]
