# Generated by Django 5.1.7 on 2025-06-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0009_remove_block_allotment_b_gender_836496_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='alloted_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_rooms', to='allotment.roomgroup'),
        ),
    ]
