# Generated by Django 5.1.7 on 2025-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectDates',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'select_dates',
            },
        ),
    ]
