# Generated by Django 5.1.7 on 2025-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectdates',
            options={'ordering': ['year', 'event_id']},
        ),
        migrations.AddField(
            model_name='selectdates',
            name='year',
            field=models.CharField(default='first_year', max_length=20),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='event_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='selectdates',
            unique_together={('event_id', 'year')},
        ),
    ]
