# Generated by Django 5.1.7 on 2025-04-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selectdates',
            table=None,
        ),
    ]
