# Generated by Django 5.1.7 on 2025-04-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0002_alter_selectdates_options_selectdates_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectdates',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='event',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Student Data Verification', 'Student Data Verification'), ('Result Declaration', 'Result Declaration'), ('Roommaking', 'Roommaking'), ('Final Allotment', 'Final Allotment'), ('Verification', 'Verification')], max_length=100),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='year',
            field=models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year')], default='first_year', max_length=20),
        ),
    ]
