# Generated by Django 5.1.7 on 2025-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0003_alter_selectdates_end_date_alter_selectdates_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectdates',
            name='year',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Fourth Year')], default='first_year', max_length=20),
        ),
    ]
