# Generated by Django 5.1.7 on 2025-05-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0004_alter_selectdates_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goi_jk_seats', models.IntegerField(default=0)),
                ('nri_fn_pio_gulf_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10)),
                ('total_seats', models.IntegerField()),
                ('ews_seats', models.IntegerField()),
                ('all_india_seats', models.IntegerField()),
                ('branch_seats', models.JSONField()),
                ('reserved_seats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminrole.reservedseat')),
            ],
            options={
                'unique_together': {('year', 'gender')},
            },
        ),
    ]
