# Generated by Django 5.1.7 on 2025-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0005_reservedseat_seatmatrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmatrix',
            name='year',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Fourth Year')], max_length=10),
        ),
    ]
