# Generated by Django 5.1.7 on 2025-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0006_alter_seatmatrix_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmatrix',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
