# Generated by Django 5.1.7 on 2025-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0007_alter_seatmatrix_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectdates',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='selectdates',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='event',
            field=models.CharField(choices=[('Open Registrations', 'Open Registrations'), ('Open Room Preferences', 'Open Room Preferences')], max_length=100),
        ),
        migrations.AlterField(
            model_name='selectdates',
            name='year',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year'), ('btech', 'Fourth Year')], default='fy', max_length=20),
        ),
        migrations.RemoveField(
            model_name='selectdates',
            name='event_id',
        ),
    ]
