# Generated by Django 5.1.7 on 2025-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0008_alter_selectdates_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('allotment_date', models.DateTimeField(auto_now_add=True)),
                ('is_manual_override', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('year', 'gender')},
            },
        ),
    ]
